name: hello-world
'on': push
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
       - name: my-step
         run: echo "hellow world"
  my-job1:
    runs-on: ubuntu-latest
    steps:
       - name: crate new folder
         run: touch ~/newfolder/sample.txt
 
