name: Build
on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: self-hosted
    steps:
      - name: Checkout Repo
        uses: actions/checkout@main
      - name: build docker image
        run: docker build -f Dockerfile .
